version: '3'

services:
  jekyll:
    image: jekyll/jekyll:3.8
    container_name: hgnc-blog
    environment:
      - JEKYLL_ENV=docker
    command: jekyll serve --force_polling --livereload
    ports:
        - 4020:4000
        - 35729:35729
    volumes:
        - .:/srv/jekyll

